# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.60.5"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
end
